Accounting/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.SignUpView.as_view(), name='index'),
    path('verify/', views.VerifyView.as_view(), name='verify'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
]

MobileAuthentication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Accounting.urls', 'Accounting'), namespace='Accounting')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounting/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.validators import RegexValidator
from django.db import transaction

from . import models


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'] = forms.CharField(
            widget=forms.TextInput(attrs={'autofocus': True}),
            label=self.fields['username'].label,
            help_text='شماره موبایل کاربر',
            required=True,
            max_length=11,
            validators=[RegexValidator(
                regex=r'09(\d{9})$',
                message="مثال : 09000000000",
            )],
            error_messages=({
                'required': 'لطفاً مقدار نام کاربری را وارد نمایید.',
            }),
        )

        self.fields['password1'].required = False
        self.fields['password2'].required = False

        self.fields['password1'].widget.attrs['autocomplete'] = 'off'
        self.fields['password2'].widget.attrs['autocomplete'] = 'off'

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = super(SignUpForm, self).clean_password2()
        if bool(password1) ^ bool(password2):
            raise forms.ValidationError("مقدار گذرواژه و تأیید گذرواژه را وارد نمایید.")
        return password2

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_active = False
        user.save()
        self.request.session['username'] = user.username
        return user


class VerifyForm(forms.Form):
    verification_code = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True}),
        label="کد تأیید",
        help_text='کد تأیید ارسالی به شماره موبایل',
        validators=[RegexValidator(
            regex=r'^[0-9]+$',
            message="مثال : 00000",
        )],
        error_messages=({
            'required': 'لطفاً کد تأیید را وارد نمایید.',
            'invalid': 'فقط عدد قابل قبول است!',
        }),
    )


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True}),
        label="نام کاربری",
        help_text='شماره موبایل کاربر',
        validators=[RegexValidator(
            regex=r'09(\d{9})$',
            message="مثال : 09000000000",
        )],
        error_messages=({
            'required': 'لطفاً نام کاربری را وارد نمایید.',
        }),
    )


class ProfileForm(forms.Form):
    GENDER_CHOICES = [
        (0, 'آقا'),
        (1, 'خانم'),
    ]
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'نام'}),
        label='نام',
        max_length=64,
        required=False,
        error_messages=({
            'required': 'لطفاً نام خود را وارد نمایید!',
            'invalid': 'مقدار وارد شده صحیح نمی باشد!',
        }),
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'نام خانوادگی'}),
        label='نام خانوادگی',
        max_length=128,
        required=False,
        error_messages=({
            'required': 'لطفاً نام خانوادگی خود را وارد نمایید!',
            'invalid': 'مقدار وارد شده صحیح نمی باشد!',
        }),
    )
    date_of_birth = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'تاریخ تولد'}),
        label='تاریخ تولد',
        help_text='تاریخ تولد کاربر',
        required=False,
        error_messages=({
            'required': 'لطفاً مقدار تاریخ تولد را وارد نمایید.',
            'invalid': 'مقدار وارد شده صحیح نمی باشد!',
        }),
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        label='جنسیت',
        required=False,
        error_messages=({
            'invalid': 'مقدار وارد شده صحیح نمی باشد!',
        }),
    )

templates/index.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ super }} Register
{% endblock %}

{% block content %}
    <section class="col-md-6 offset-md-3 mt-4">

        <div class="card">
            <div class="card-header">
                <h4>ثبت نام در سیستم</h4>
            </div>
            <div class="card-body">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}مهم : {% endif %}
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-block" value="ثبت نام">
            </form>

            </div>

            <div class="card-footer">
                <a href="{% url 'Accounting:login' %}" class="btn btn-success btn-block">ورود به سیستم</a>
            </div>
        </div>

    </section>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
       $('#div_id_password1').addClass('d-none')
       $('#div_id_password2').addClass('d-none')
    });
</script>
{% endblock %}

templates/login.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ super }} Login
{% endblock %}

{% block content %}
    <section class="col-md-6 offset-md-3 mt-4">

        <div class="card">
            <div class="card-header">
                <h4>ورود به سیستم</h4>
            </div>
            <div class="card-body">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}مهم : {% endif %}
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-block" value="ورود">
            </form>

            </div>
        </div>

    </section>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
       $('#div_id_password1').addClass('d-none')
       $('#div_id_password2').addClass('d-none')
    });
</script>
{% endblock %}

templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <title>Mobile Authentication | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    {% block styles %}
    {% endblock %}
</head>
<body dir="rtl">
    <div class="container">

        <div class="row">
            {% block content %}
            {% endblock %}
        </div>

    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/profile.html
{% extends 'master.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    {{ super }} Profile
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendor/pwt.datepicker/persian-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <section class="col-md-6 offset-md-3 mt-4">

        <div class="card">
            <div class="card-header">
                <h4>پروفایل</h4>
            </div>
            <div class="card-body">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}مهم : {% endif %}
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-block" value="ذخیره تغییرات">
            </form>

            </div>

            <div class="card-footer">
                <a href="{% url 'Accounting:logout' %}" class="btn btn-danger btn-block">خروج از سیستم</a>
            </div>
        </div>

    </section>

{% endblock %}

{% block script %}
    <script src="{% static 'vendor/pwt.datepicker/persian-date.min.js' %}"></script>
    <script src="{% static 'vendor/pwt.datepicker/persian-datepicker.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $("#id_date_of_birth").persianDatepicker({
                format: 'YYYY/MM/DD',
            });
        });
    </script>
{% endblock %}

templates/verify.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ super }} Verify
{% endblock %}

{% block content %}
    <section class="col-md-6 offset-md-3 mt-4">

        <div class="card">
            <div class="card-header">
                <h4>تأیید شماره موبایل</h4>
            </div>
            <div class="card-body">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}مهم : {% endif %}
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-block" value="تأیید">
            </form>

            </div>
        </div>

    </section>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
       $('#div_id_password1').addClass('d-none')
       $('#div_id_password2').addClass('d-none')
    });
</script>
{% endblock %}